# Generated by Django 3.2.19 on 2023-06-28 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('alias', models.TextField(null=True)),
                ('actors', models.TextField(null=True)),
                ('cover', models.TextField(null=True)),
                ('directors', models.TextField(null=True)),
                ('douban_score', models.FloatField(null=True)),
                ('douban_votes', models.IntegerField(null=True)),
                ('imdb_id', models.TextField(null=True)),
                ('languages', models.TextField(null=True)),
                ('mins', models.IntegerField(null=True)),
                ('official_site', models.TextField(null=True)),
                ('regions', models.TextField(null=True)),
                ('release_date', models.TextField(null=True)),
                ('storyline', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-douban_votes', '-douban_score'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('favorite_movies', models.ManyToManyField(default=None, to='userWeb.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
