# Generated by Django 3.2.19 on 2023-06-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='users_who_like', to='userWeb.Movie'),
        ),
    ]
