# Generated by Django 3.2.19 on 2023-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0002_auto_20230628_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
